GET https://localhost:3000/movies

###

POST https://localhost:3000/movies
Content-Type: application/json

{
    "movieID": "1564573521",
    "title": "Hobbit, there and back again",
    "runtime": 185,
    "genre": ["adventure", "action", "fantasy"]
}